export const teamPresetsConfig = Object.freeze({
  id: "team-presets",
  storageKey: "ppbui:team-presets:v2",
  legacyStorageKey: "ppbui:team-presets:v1",
  actionTimeoutMs: 8000,
  selectors: {
    hud: ".pokeidle-team-hud",
    hudList: ".pokeidle-team-hud__list",
    hudCard: ".pokeidle-team-card:not(.pokeidle-team-card--empty)",
    hudCardName: ".pokeidle-team-card__name",
    teamPanel: ".pokeidle-team-panel",
    teamBody: ".pokeidle-panel__body",
    teamRoster: ".team-section--roster",
    teamProfile: ".team-section--profile",
    teamSlot: ".team-slot",
    teamActiveAction: ".team-active-state",
    teamRemoveAction: ".team-actions .pokeidle-btn--danger",
    teamOrderButton: "button",
    picker: ".team-equip-picker",
    pickerCard: ".team-equip-card",
    teamMenuAction: 'button[data-menu-id="team"]',
  },
});
