export const config = {
  id: "marks-shop",
  selectors: {
    root: ".npc-shop-window",
    titlebar: ":scope > .pokeidle-panel__titlebar",
    body: ":scope > .pokeidle-panel__body",
    search: ".npc-shop__search",
    shell: ".npc-shop__shell",
    sidebar: ".npc-shop__sidebar",
    tabs: ".npc-shop__tabs > button",
    content: ".npc-shop__content",
    heading: ".npc-shop__content-heading",
    listBase: ".npc-shop__list",
    category: ".npc-shop__category",
    buy: ".npc-shop__buy-grid",
    buyCard: ".npc-shop__buy-card",
    purchaseButton: ".npc-shop__purchase-button",
    customPurchase: ".npc-shop__custom-purchase",
    buyQuantity: '.npc-shop__custom-purchase input[type="number"]',
    customButton: ".npc-shop__custom-button",
    itemCategory: ".npc-shop__item-category",
    sellList: ".npc-shop__list--sell",
    sellRow: ".npc-shop__sell-row",
    sellQuantity: ".npc-shop__sell-quantity input",
    pokemon: ".npc-shop__list--pokemon",
    row: ".npc-shop__pokemon-row",
    checkbox: 'input[type="checkbox"]',
    name: ".npc-shop__item-info > b",
    quality: ".npc-shop__quality",
    rarity: ".npc-shop__rarity",
    footer: ".npc-shop__sell-footer",
    sell: ".npc-shop__sell-button",
    buyback: ".npc-shop__list--buyback",
    buybackRow: ".npc-shop__buyback-row",
    buybackButton: ".npc-shop__buyback-button",
    close: ".npc-shop__close",
  },
};
